platform :ios, '10.0'
target 'GraduateProj' do
pod 'AFNetworking', '~> 3.1.0'
pod "Masonry", "~> 1.0.2"
pod "IQKeyboardManager", "~> 4.0.9"
pod "MJExtension", "~> 2.5.1"
pod "MJRefresh", "~> 3.1.12"
pod "SDWebImage", "~> 3.8.2"
pod "MBProgressHUD", "~> 1.0.0"
pod "RTRootNavigationController", "~> 0.5.25"
end

